name: Testing GitHub Actions

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: "Running Python Script"
        run: python main.py
        
      - uses: actions/checkout@v2
        with: 
          token: ${{secrets.PAT}}
      - name: "committing and pushing"
        run: |
          git config --global user.email "tamilts124new@users.noreply.github.com"
          git config --global user.name "tamilts124new"
          # git remote set-url origin https://github.com/tamilts124new/reimagined-dollop.git
          # git add .
          # git commit -m "updated log file"
          git commit -a -m "updated logs" --allow-empty
          git push origin master
