name: Testing GitHub Actions

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: "Running Python Script"
        run: python main.py
        
        
      - name: "committing and pushing"
        run: |
          git config --global user.email "tamilts124+new@gmail.com"
          git config --global user.name "tamilts124new"
          git remote set-url origin https://github.com/tamilts124new/reimagined-dollop.git
          git add .
          git commit -m "updated log file"
          git push origin master
